queue_rules:
  - name: default
    conditions:
      - label=ready

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label!=abc
    actions:
      queue:
        name: default
