queue_rules:
  - name: default
    conditions:
      - label=ready
      - check-success=pr-ci-on-bts

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label!=abc
    actions:
      queue:
        name: default
