queue_rules:
  - name: default
    conditions:
      - base=master

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
    actions:
      queue:
        name: default
