name: pull-request-ci
on:
  issue_comment:
    types: [created]

jobs:
  pr-ci-on-bts:
    if: github.event.issue.pull_request && github.event.comment.body == 'test please'
    runs-on: ubuntu-latest

    steps:
      - name: Check environment variables
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_PR_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "pr_number": ${{ github.event.issue.number }}, "context": "pr-ci-on-bts" }'
