name: pull-request-ci
on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  security-events: write
  statuses: write
  
jobs:
  pr-ci-on-bts:
    if: github.event.issue.pull_request && github.event.comment.body == 'test please'
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/check-runs \
            -d '{"name":"pr-ci-on-bts","head_sha":"${{ github.event.pull_request.head.sha }}","status":"in_progress"}'
  
      - uses: actions/checkout@v1
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: pr-ci-on-bts
          conclusion: success
          output: |
            {"summary": "no summary"}
