name: pull-request-ci
on:
  issue_comment:
    types: [created]

jobs:
  pr-ci-on-bts:
    if: github.event.issue.pull_request && github.event.comment.body == 'test please'
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        shell: bash
        run: |
          echo "hello"
          echo ${{ github.repository }}
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{ github.event.workflow_run.conclusion }}
          curl --request POST \
                    --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
                    --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                    --header 'content-type: application/json' \
                    --data '{
                      "state": "SUCCESS",
                      "context": "pr-ci-on-bts",
                      "target_url": "${{ github.event.workflow_run.html_url }}"
                      }' \
                    --fail
